CREATE TABLE [dbo].[City]
(
	[ID] INT NOT NULL PRIMARY KEY, 
    [NAME] VARCHAR(17) NOT NULL, 
    [COUNTRYCODE] VARCHAR(3) NOT NULL, 
    [DISTRICT] VARCHAR(20) NOT NULL, 
    [POPULATION] INT NOT NULL
)
